# fly.toml app configuration file generated for cuber3 on 2026-04-12T00:02:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mi-taller-docker"
primary_region = "scl"  # Santiago de Chile

[build]
  builder = "docker"
  dockerfile = "Dockerfile.fly"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[services.ports]]
  port = 80
  handlers = ["http"]

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]
