app = "mi-taller-docker"
primary_region = "scl"

[build]
  builder = "docker"
  dockerfile = "Dockerfile.fly"

# Servicio frontend
[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# Servicio backend
[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

[env]
  FLASK_ENV = "production"
  POSTGRES_USER = "postgres"
